apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: {{ .Values.namespace }} 
spec:
  selector: 
    app: nginx
    matchLabels:
  ports:
    - protocol: TCP
        port: 80
        targetPort: 3000
